from __future__ import annotations

from pathlib import Path
from typing import Any

from audiocover.simple_timbre import apply_simple_timbre, train_simple_timbre
from audiocover.workers.json_worker import serve


def capabilities(_: dict[str, Any]) -> dict[str, Any]:
    return {
        "available": True,
        "actions": ["train", "convert"],
        "description": "Built-in lightweight timbre profile worker",
    }


def train(payload: dict[str, Any]) -> dict[str, Any]:
    dataset_wavs = Path(payload["dataset_wavs"])
    output_dir = Path(payload["output_dir"])
    sample_rate = int(payload.get("sample_rate") or 48000)
    output_dir.mkdir(parents=True, exist_ok=True)
    profile = train_simple_timbre(dataset_wavs, output_dir / "simple_timbre.json", sample_rate)
    return {
        "backend": "simple-timbre",
        "conversion_backend": "managed",
        "simple_profile_path": str(profile),
        "model_path": None,
        "index_path": None,
        "notes": "Built-in lightweight profile generated by the packaged simple-timbre worker.",
    }


def convert(payload: dict[str, Any]) -> dict[str, Any]:
    input_path = Path(payload["input"])
    output_path = Path(payload["output"])
    profile_path = Path(payload["simple_profile_path"])
    output_path.parent.mkdir(parents=True, exist_ok=True)
    apply_simple_timbre(input_path, output_path, profile_path)
    return {"output": str(output_path)}


def main() -> None:
    serve({"capabilities": capabilities, "train": train, "convert": convert})


if __name__ == "__main__":
    main()
